Repository Busan-Dinosaur/Foodbowl-Backend, pull requests merged in 2023-10, with the labels that each got.

#180 Feature/#107 이름으로 가게를 검색하는 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
  src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreSearchResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreSearchResponses.java
  src/main/java/org/dinosaur/foodbowl/domain/store/exception/StoreExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreController.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerTest.java
  src/test/java/org/dinosaur/foodbowl/test/config/TestQuerydslConfig.java
Labels: backend, feature

#183 Feature/#176 북마크 가게 리뷰 목록 조회 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/ReviewPageResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
Labels: backend, feature

#184 Feature/#132 학교 주변 리뷰 목록 조회 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/store/exception/SchoolExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/SchoolRepository.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/persistence/SchoolRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/test/IntegrationTest.java
  src/test/java/org/dinosaur/foodbowl/test/PersistenceTest.java
  src/test/java/org/dinosaur/foodbowl/test/persister/StoreSchoolTestPersister.java
Labels: backend, feature

#185 Feature/#117 유저 닉네임 검색 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/follow/application/FollowCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/application/dto/MemberToFollowingsDto.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/dto/FollowerAndFollowingDto.java
  src/main/java/org/dinosaur/foodbowl/domain/member/application/MemberCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/member/application/MemberService.java
  src/main/java/org/dinosaur/foodbowl/domain/member/dto/response/MemberSearchResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/member/dto/response/MemberSearchResponses.java
  src/main/java/org/dinosaur/foodbowl/domain/member/persistence/MemberCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberController.java
  src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreSearchResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/application/FollowCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/application/dto/MemberToFollowingsDtoTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/persistence/dto/FollowerAndFollowingDtoTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/application/MemberCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/application/MemberServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/presentation/MemberControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/test/config/TestQuerydslConfig.java
Labels: backend, feature

#186 Feature/#135 유저 프로필 리뷰 목록 조회 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
Labels: backend, feature

#188 Feature/#174 팔로우한 유저의 가게를 조회하는 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/member/dto/response/MemberSearchResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/application/dto/StoreToReviewCountDto.java
  src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/review/persistence/dto/StoreReviewCountDto.java
  src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
  src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreMapBoundResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/StoreMapBoundResponses.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreController.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/application/dto/MemberToFollowingsDtoTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/application/MemberServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerTest.java
Labels: backend, feature

#189 Feature/#131 북마크 가게 목록을 조회하는 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreController.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerTest.java
Labels: backend, feature

#191 Feature/#181 로그아웃 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/auth/application/AuthService.java
  src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthController.java
  src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/auth/application/AuthServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthControllerTest.java
Labels: backend, feature

#192 Feature/#134 가게 리뷰 목록 조회 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/application/ReviewService.java
  src/main/java/org/dinosaur/foodbowl/domain/review/domain/vo/ReviewFilter.java
  src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewContentResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/StoreReviewResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/review/exception/ReviewExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewCustomServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/domain/vo/ReviewFilterTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerTest.java
Labels: backend, feature

#194 Feature/#193 리뷰가 존재하지 않을 때 리뷰 페이지 정보에서 예외가 발생한다.
  src/main/java/org/dinosaur/foodbowl/domain/review/dto/response/ReviewPageInfo.java
  src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewCustomRepository.java
  src/test/java/org/dinosaur/foodbowl/domain/review/application/ReviewServiceTest.java
Labels: backend, bug

#199 Feature/#51 모니터링 환경을 구성한다.
  build.gradle
  src/main/java/org/dinosaur/foodbowl/FoodbowlApplication.java
  src/main/java/org/dinosaur/foodbowl/global/config/SecurityConfig.java
  src/main/java/org/dinosaur/foodbowl/global/presentation/MemberArgumentResolver.java
  src/main/java/org/dinosaur/foodbowl/global/presentation/jwt/JwtAuthenticationFilter.java
  src/main/java/org/dinosaur/foodbowl/global/presentation/jwt/JwtUser.java
  src/main/java/org/dinosaur/foodbowl/global/presentation/security/ActuatorProperties.java
  src/main/resources/application.yml
  src/test/java/org/dinosaur/foodbowl/test/PresentationTest.java
  src/test/java/org/dinosaur/foodbowl/test/config/TestPropertyConfig.java
Labels: backend, infra

#202 Feature/#201 DB 레플리케이션 환경을 구성한다.
  build.gradle
  src/main/java/org/dinosaur/foodbowl/global/infra/db/DataSourceConfig.java
  src/main/java/org/dinosaur/foodbowl/global/infra/db/DataSourceType.java
  src/main/java/org/dinosaur/foodbowl/global/infra/db/RoutingDataSource.java
  src/main/resources/application.yml
  src/test/java/org/dinosaur/foodbowl/test/PersistenceTest.java
Labels: backend, feature, infra
