Repository Busan-Dinosaur/Foodbowl-Backend, pull requests merged in 2023-08, with the labels that each got.

#94 Feature/#91 요청 발생 시 회원을 가져오는 방법을 변경한다.
  src/main/java/org/dinosaur/foodbowl/domain/healthcheck/application/HealthCheckService.java
  src/main/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckController.java
  src/main/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerImpl.java
  src/main/java/org/dinosaur/foodbowl/domain/member/domain/Member.java
  src/main/java/org/dinosaur/foodbowl/domain/member/exception/MemberExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/member/persistence/MemberRepository.java
  src/main/java/org/dinosaur/foodbowl/global/config/WebConfig.java
  src/main/java/org/dinosaur/foodbowl/global/presentation/Auth.java
  src/main/java/org/dinosaur/foodbowl/global/presentation/MemberArgumentResolver.java
  src/test/java/org/dinosaur/foodbowl/PersistenceTest.java
  src/test/java/org/dinosaur/foodbowl/PresentationTest.java
  src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberRepositoryTest.java
Labels: backend, feature, refactor

#97 수정된 DB에 맞게 엔티티를 수정한다.
  .github/workflows/deploy-dev.yml
  docker/docker-compose-build.yml
  docker/docker-compose-local.yml
  src/main/java/org/dinosaur/foodbowl/domain/member/domain/Member.java
  src/main/java/org/dinosaur/foodbowl/domain/review/domain/ReviewThumbnail.java
  src/main/java/org/dinosaur/foodbowl/domain/review/persistence/ReviewThumbnailRepository.java
  src/main/java/org/dinosaur/foodbowl/global/persistence/AuditingEntity.java
Labels: backend, feature

#101 Feature/#100 카테고리 목록 조회 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
  src/main/java/org/dinosaur/foodbowl/domain/store/domain/Category.java
  src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/CategoryResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/CategoryResponses.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/CategoryRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreController.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/persistence/MemberRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/persistence/CategoryRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerTest.java
  src/test/java/org/dinosaur/foodbowl/test/IntegrationTest.java
  src/test/java/org/dinosaur/foodbowl/test/PersistenceTest.java
  src/test/java/org/dinosaur/foodbowl/test/PresentationTest.java
Labels: backend, feature

#116 Feature/#102 팔로우 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/follow/application/FollowService.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/domain/Follow.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/exception/FollowExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowController.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/member/exception/MemberExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/member/persistence/FollowRepository.java
  src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerTest.java
  src/test/java/org/dinosaur/foodbowl/test/IntegrationTest.java
  src/test/java/org/dinosaur/foodbowl/test/PersistenceTest.java
  src/test/java/org/dinosaur/foodbowl/test/PresentationTest.java
  src/test/java/org/dinosaur/foodbowl/test/persister/FollowTestPersister.java
  src/test/java/org/dinosaur/foodbowl/test/persister/MemberTestPersister.java
Labels: backend, feature

#128 Feature/#109 팔로우 취소 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/follow/application/FollowService.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/exception/FollowExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowController.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/global/exception/ErrorResponse.java
  src/main/java/org/dinosaur/foodbowl/global/exception/GlobalExceptionHandler.java
  src/test/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerTest.java
  src/test/java/org/dinosaur/foodbowl/test/PresentationTest.java
Labels: backend, feature

#129 Feature/#123 팔로워 삭제 기능을 구현한다.
  .github/workflows/pr-test.yml
  src/main/java/org/dinosaur/foodbowl/domain/auth/dto/response/TokenResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/application/FollowService.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/exception/FollowExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowController.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/store/dto/response/CategoryResponse.java
  src/main/java/org/dinosaur/foodbowl/global/exception/ExceptionResponse.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerTest.java
Labels: backend, feature

#142 Feature/#89 Jacoco를 이용해 테스트 커버리지를 측정한다.
  .github/workflows/pr-test.yml
  build.gradle
  lombok.config
  src/main/java/org/dinosaur/foodbowl/domain/auth/application/NicknameGenerator.java
  src/main/java/org/dinosaur/foodbowl/global/util/EncryptUtils.java
  src/test/java/org/dinosaur/foodbowl/domain/auth/application/apple/AppleTokenParserTest.java
  src/test/java/org/dinosaur/foodbowl/domain/blame/domain/BlameTest.java
  src/test/java/org/dinosaur/foodbowl/domain/healthcheck/application/HealthCheckServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/domain/BookmarkTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/domain/MemberRoleTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/domain/MemberThumbnailTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/domain/RoleTest.java
  src/test/java/org/dinosaur/foodbowl/domain/photo/domain/ReviewPhotoTest.java
  src/test/java/org/dinosaur/foodbowl/domain/photo/domain/ThumbnailTest.java
  src/test/java/org/dinosaur/foodbowl/domain/review/domain/ReviewTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/domain/CategoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/domain/SchoolTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/domain/StoreSchoolTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/domain/StoreTest.java
Labels: backend, infra

#144 Feature/#143 사진 로컬 이미지 경로를 설정한다.
  src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploader.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewController.java
Labels: backend, feature

#140 Feature/#137 타인의 팔로워 목록 조회 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/application/FollowService.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/dto/response/OtherUserFollowerResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/persistence/FollowRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowController.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/healthcheck/presentation/HealthCheckControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/member/domain/Member.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/store/presentation/StoreControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/domain/MemberTest.java
  src/test/java/org/dinosaur/foodbowl/global/presentation/jwt/JwtAuthorizationExtractorTest.java
Labels: backend, feature

#145 Feature/#124 북마크 추가 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/auth/presentation/AuthControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkService.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/domain/Bookmark.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/exception/BookmarkExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/presentation/BookmarkController.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/presentation/BookmarkControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/member/persistence/BookmarkRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/review/presentation/ReviewControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/store/application/StoreService.java
  src/main/java/org/dinosaur/foodbowl/domain/store/exception/StoreExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepository.java
  src/test/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/bookmark/domain/BookmarkTest.java
  src/test/java/org/dinosaur/foodbowl/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/bookmark/presentation/BookmarkControllerTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/application/StoreServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/store/persistence/StoreRepositoryTest.java
Labels: backend, feature

#147 Feature/#138 타인의 팔로잉 목록 조회 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/follow/application/FollowService.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/dto/response/OtherUserFollowingResponse.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowController.java
  src/main/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerDocs.java
  src/main/java/org/dinosaur/foodbowl/domain/photo/application/PhotoLocalUploader.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/application/FollowServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/follow/presentation/FollowControllerTest.java
Labels: backend, feature

#154 Feature/#125 북마크 삭제 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkService.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/exception/BookmarkExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/persistence/BookmarkRepository.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/presentation/BookmarkController.java
  src/main/java/org/dinosaur/foodbowl/domain/bookmark/presentation/BookmarkControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/bookmark/application/BookmarkServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/bookmark/persistence/BookmarkRepositoryTest.java
  src/test/java/org/dinosaur/foodbowl/domain/bookmark/presentation/BookmarkControllerTest.java
Labels: backend, feature

#160 Feature/#149 프로필 정보를 수정하는 기능을 구현한다.
  src/main/java/org/dinosaur/foodbowl/domain/member/application/MemberService.java
  src/main/java/org/dinosaur/foodbowl/domain/member/domain/Member.java
  src/main/java/org/dinosaur/foodbowl/domain/member/domain/vo/Introduction.java
  src/main/java/org/dinosaur/foodbowl/domain/member/domain/vo/Nickname.java
  src/main/java/org/dinosaur/foodbowl/domain/member/dto/request/UpdateProfileRequest.java
  src/main/java/org/dinosaur/foodbowl/domain/member/exception/MemberExceptionType.java
  src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberController.java
  src/main/java/org/dinosaur/foodbowl/domain/member/presentation/MemberControllerDocs.java
  src/test/java/org/dinosaur/foodbowl/domain/member/application/MemberServiceTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/domain/MemberTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/domain/vo/IntroductionTest.java
  src/test/java/org/dinosaur/foodbowl/domain/member/presentation/MemberControllerTest.java
Labels: backend, feature
